In [1]:
import torch
import numpy as np
import time

In [2]:
in_image = torch.randn(2,5,5)
nn = torch.nn.Conv2d(2, 3, 1, padding=0, stride=1)

out_image = nn(in_image)

out_channels = nn.out_channels
in_channels = nn.in_channels
in_height = in_image.size(1)
in_width = in_image.size(2)
kernel_size = nn.kernel_size[0]
out_height = out_image.size(1)
out_width = out_image.size(2)
weights = nn.weight.detach()
stride = nn.stride[0]
padding = nn.padding[0]
bias = nn.bias
print(weights.size())
print("Output size: ", out_image.size())

torch.Size([3, 2, 1, 1])
Output size:  torch.Size([3, 5, 5])


In [3]:
def run_their_implementation():
    now=time.time()
    in_width_p = in_width + padding * 2
    in_height_p = in_height + padding * 2

    size_p = in_height_p * in_width_p
    in_dim = size_p * in_channels
    out_dim = out_height * out_width * out_channels
    res = torch.zeros((out_dim, in_dim))

    # build row fillers
    len_rows = (in_channels - 1) * size_p + (kernel_size - 1) * in_width_p + kernel_size
    channels = torch.zeros((out_channels, len_rows))

    for i_out in range(out_channels):
        for i_in in range(in_channels):
            i_p = i_in * size_p
            for k in range(kernel_size):
                start = i_p + k * in_width_p
                end = start + kernel_size
                channels[i_out, start:end] = weights[i_out, i_in, k]

        for i_out_height in range(out_height):
            for i_out_width in range(out_width):
                start = i_out_height * stride * in_width_p + i_out_width * stride
                end = start + len_rows
                output = i_out * out_height * out_width + i_out_height * out_width + i_out_width
                res[output, start:end] = channels[i_out]

    # remove padding
    padding_rows = []
    for i_in in range(in_channels):
        for i_in_height in range(in_height_p):
            for i_in_width in range(in_width_p):
                if i_in_width < padding or i_in_width >= padding + in_width:
                    padding_rows.append(i_in * size_p + i_in_height * in_width_p + i_in_width)

            if i_in_height < padding or i_in_height >= padding + in_height:
                start = i_in * size_p + i_in_height * in_width_p
                end = start + in_width_p
                padding_rows = padding_rows + list(range(start, end))

    padding_rows = list(np.unique(np.array(padding_rows)))  # delete duplicates

    lc = torch.from_numpy(np.delete(res.numpy(), padding_rows, axis=1)).detach()

    if bias is None:
        ret_bias = torch.zeros(out_width * out_height * out_channels)
    else:
        ret_bias = torch.repeat_interleave(bias, out_width * out_height)
    print("Their implementation took: ", time.time()-now)
    return lc

In [106]:
def run_my_implementation():
    now=time.time()

    final_matrix = torch.zeros((in_width * in_height * in_channels, out_width * out_height * out_channels))

    flattened_weights = weights.flatten()

    offset = int((kernel_size - 1) / 2)
    kernel_size_kadenz = kernel_size * kernel_size
    output_image_kadenz = out_width * out_height
    final_matrix_col_indices = torch.zeros(out_width * out_height * out_channels)
    final_matrix_weight_indices = torch.zeros(weights.flatten().size())

    for channel_in_idx in range(in_channels):
        # Only iterate over the ones where the kernel fits
        for col_in in range(offset-padding, in_height - offset + padding, stride):
            for row_in in range(offset-padding, in_width - offset + padding, stride):
                # Indices of the output
                col_out = int((col_in - offset + padding)/stride)
                row_out = int((row_in - offset + padding)/stride)

                #print("Channel: ", channel_in_idx, "Col: ", col_in, "Row: ", row_in, "Column out: ", col_out, "Row out: ", row_out)


                # Final matrix column indices is the relative position inside the output image
                final_matrix_col_indices.fill_(0)  # Resetting the tensor to zero
                first_idx = (col_out) * out_width + row_out
                num_elements_to_fill = (len(final_matrix_col_indices) - first_idx) // (output_image_kadenz) + 1
                fill_indices = first_idx + torch.arange(num_elements_to_fill) * (output_image_kadenz)
                # Clamp fill_indices to the length of final_matrix_col_indices to avoid index out of bounds
                fill_indices = fill_indices[fill_indices < len(final_matrix_col_indices)]
                # Fill in the tensor
                final_matrix_col_indices[fill_indices] = 1

                
                kernel_count_idx = 0
                for kernel_col_idx in range(col_in - offset, col_in + offset + 1):
                    for kernel_row_idx in range(row_in - offset, row_in + offset + 1):
                        if kernel_col_idx < 0 or kernel_row_idx < 0 or kernel_col_idx >= in_height or kernel_row_idx >= in_width:
                            kernel_count_idx += 1
                            continue
                
                        # Final matrix row index is the relative position inside the input image
                        final_matrix_row_idx = (kernel_col_idx * in_width + kernel_row_idx) + (channel_in_idx * in_width * in_height)
                        #print("Final matrix row idx: ", final_matrix_row_idx)

                        # Final matrix weight indices is the relative position inside the kernel -> kernel_count_idx
                        # It has to be across the channels with kadenz of the kernel size
                        final_matrix_weight_indices.fill_(0)  # Resetting the tensor to zero
                        num_elements_to_fill = (len(final_matrix_weight_indices) - kernel_count_idx) // (kernel_size_kadenz) + 1
                        fill_weight_indices = kernel_count_idx + torch.arange(num_elements_to_fill) * (kernel_size_kadenz)
                        # Clamp fill_weight_indices to the length of final_matrix_weight_indices to avoid index out of bounds
                        fill_weight_indices = fill_weight_indices[fill_weight_indices < len(final_matrix_weight_indices)]
                        # Fill in the tensor
                        final_matrix_weight_indices[fill_weight_indices] = 1

                        weight_mask = final_matrix_weight_indices == 1
                        # Select every in_channel'th element
                        weight_mask = torch.arange(len(weight_mask))[weight_mask]
                        weight_mask = weight_mask[channel_in_idx::in_channels]
                        #print("Weight mask: ", weight_mask)
                        #print("Weights: ", flattened_weights[weight_mask])
                        #print("Final matrix row idx: ", final_matrix_row_idx)
                        #print("Final matrix col indices: ", final_matrix_col_indices)
                        # Fill the matrix
                        final_matrix[final_matrix_row_idx, final_matrix_col_indices == 1] = flattened_weights[weight_mask]

                        kernel_count_idx += 1
    
    print("My implementation took: ", time.time()-now)
    return final_matrix

In [116]:
in_image = torch.randn(4,5,5)
nn = torch.nn.Conv2d(4, 3, 3, padding=2, stride=2)

out_image = nn(in_image)
out_channels = nn.out_channels
in_channels = nn.in_channels
in_height = in_image.size(1)
in_width = in_image.size(2)
kernel_size = nn.kernel_size[0]
out_height = out_image.size(1)
out_width = out_image.size(2)
weights = nn.weight.detach()
stride = nn.stride[0]
padding = nn.padding[0]
bias = nn.bias
print(weights.size())
print("Output size: ", out_image.size())
print("Matrix size: ", in_width * in_height * in_channels, out_width * out_height * out_channels)

torch.Size([3, 4, 3, 3])
Output size:  torch.Size([3, 4, 4])
Matrix size:  100 48


In [118]:
lc = run_their_implementation()
lc = lc.transpose(0,1)
final_matrix = run_my_implementation()
torch.allclose(lc, final_matrix, atol=1e-06, rtol=1e-06)
#for row_idx in range(len(lc)):
#    if not torch.allclose(lc[row_idx], final_matrix[row_idx], atol=1e-06, rtol=1e-06):
#        print("Row: ", row_idx)
#        print(lc[row_idx])
#        print(final_matrix[row_idx])
#        print(torch.allclose(lc[row_idx], final_matrix[row_idx], atol=1e-06, rtol=1e-06))

Their implementation took:  0.002974987030029297
Channel:  0 Col:  -1 Row:  -1 Column out:  0 Row out:  0
Channel:  0 Col:  -1 Row:  1 Column out:  0 Row out:  1
Channel:  0 Col:  -1 Row:  3 Column out:  0 Row out:  2
Channel:  0 Col:  -1 Row:  5 Column out:  0 Row out:  3
Channel:  0 Col:  1 Row:  -1 Column out:  1 Row out:  0
Channel:  0 Col:  1 Row:  1 Column out:  1 Row out:  1
Channel:  0 Col:  1 Row:  3 Column out:  1 Row out:  2
Channel:  0 Col:  1 Row:  5 Column out:  1 Row out:  3
Channel:  0 Col:  3 Row:  -1 Column out:  2 Row out:  0
Channel:  0 Col:  3 Row:  1 Column out:  2 Row out:  1
Channel:  0 Col:  3 Row:  3 Column out:  2 Row out:  2
Channel:  0 Col:  3 Row:  5 Column out:  2 Row out:  3
Channel:  0 Col:  5 Row:  -1 Column out:  3 Row out:  0
Channel:  0 Col:  5 Row:  1 Column out:  3 Row out:  1
Channel:  0 Col:  5 Row:  3 Column out:  3 Row out:  2
Channel:  0 Col:  5 Row:  5 Column out:  3 Row out:  3
Channel:  1 Col:  -1 Row:  -1 Column out:  0 Row out:  0
Channe

True

In [60]:
lc.size()

torch.Size([25, 147])

In [61]:
final_matrix.size()

torch.Size([25, 147])

In [62]:
final_matrix[0]

tensor([-0.2668, -0.2668, -0.2668,  0.0000,  0.0000,  0.0000,  0.0000, -0.2668,
        -0.2668, -0.2668,  0.0000,  0.0000,  0.0000,  0.0000, -0.2668, -0.2668,
        -0.2668,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000, -0.2002, -0.2002, -0.2002,  0.0000,  0.0000,  0.0000,  0.0000,
        -0.2002, -0.2002, -0.2002,  0.0000,  0.0000,  0.0000,  0.0000, -0.2002,
        -0.2002, -0.2002,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.2936,  0.29

In [63]:
lc[0]

tensor([-0.0394,  0.1808,  0.0849,  0.0000,  0.0000,  0.0000,  0.0000, -0.1368,
        -0.0201,  0.2318,  0.0000,  0.0000,  0.0000,  0.0000,  0.0721, -0.0343,
        -0.2668,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0103, -0.1317, -0.2827,  0.0000,  0.0000,  0.0000,  0.0000,
        -0.2585, -0.0390, -0.1923,  0.0000,  0.0000,  0.0000,  0.0000,  0.1356,
         0.1727, -0.2002,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000, -0.2331, -0.21

In [56]:
weights.flatten()

tensor([-0.1842,  0.1688, -0.2742,  0.0619, -0.2409,  0.2470,  0.0566, -0.2970,
        -0.0433, -0.1951, -0.3255,  0.0648,  0.2315,  0.2613,  0.1575,  0.0743,
        -0.0922, -0.0474,  0.2592, -0.1582, -0.3085, -0.2735,  0.0195, -0.0584,
        -0.1964, -0.1308,  0.2696])

In [303]:
torch.round(weights.flatten() * 1000) / 1000

tensor([-0.1110,  0.1750, -0.0280, -0.1190,  0.1040,  0.2290, -0.1070,  0.0580,
        -0.1630,  0.0610, -0.1210,  0.2310, -0.0050,  0.1360,  0.0930,  0.1820,
        -0.0690, -0.0980,  0.1880,  0.1880,  0.0360,  0.1740, -0.0710,  0.1190,
         0.2290, -0.1090, -0.0620, -0.0430,  0.1360, -0.1790, -0.0440, -0.0660,
        -0.1650, -0.0590,  0.0040,  0.1840,  0.1790, -0.0890, -0.0310,  0.1200,
        -0.1570, -0.2080, -0.1040, -0.1940, -0.1690,  0.1290, -0.0350, -0.0760,
         0.1770, -0.2070, -0.1460, -0.1580,  0.1880, -0.1750])

In [222]:
final_matrix_weight_indices = torch.tensor([-0.0289, -0.1273,  0.0912,  0.1214, -0.1635,  0.0009])
torch.arange(len(final_matrix_weight_indices  == 1)) % in_channels == 0

tensor([ True, False,  True, False,  True, False])